// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SERVER_P;

{ITE} {LCID:00000804:00000804} {}
{ITE} {DFMFileType} {SERVER.dfm}
{ITE} {RCFileType} {SERVER_P_DRC.rc}

{$R 'SERVER.dfm' Form1:TForm}
{$R 'SERVER_P_DRC.res' 'SERVER_P_DRC.rc'}

{$E CHS}

begin
end.